# Generated by Django 3.2.3 on 2021-05-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
