# Generated by Django 3.2.3 on 2021-05-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_rename_author_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
